### ISSUE TITLE
404 when using the package under a sub-directory

### ISSUE THREAD

**Issue by fedebabrauskas** [noahjohn9259/react-clear-cache#11]
Hi there!
I'm having a problem when using this package under a sub-directory.

When your app is hosted under a sub-directory like `example.com/admin`, the request made to `/meta.json` returns 404 (Not Found) because is trying to request ` example.com/meta.json` instead of `example.com/admin/meta.json`.

One quick solution could be append `window.location.pathname` to the fetch's url `${window.location.pathname}/meta.json`.

**Comment by noahjohn9259** [comment]
hi @fedebabrauskas , sure will update the path location

**Comment by kris-pl83** [comment]
Hi,
In my project it's working on localhost but not after deploying to our server.

The problem is that startpage path of the web app is different from `context-root` and meta.json is stored under context-root path.

So we have something like this: `http://host/context-root/startpage`
But we need to fetch: `http://host/context-root/meta.json`

The proposed solution:
`${window.location.pathname}/meta.json` 
is not working because it's pointing to `http://host/context-root/startpage/meta.json`

To make it work with the context root path we need to change it to:
`window.location.pathname.substring(0, window.location.pathname.indexOf("/",2))/meta.json`

**Comment by fedebabrauskas** [comment]
As @kris-pl83 said, we can't use `window.location.pathname` for all scenarios.

We could improve it to match more cases: `window.location.pathname.substring(0, window.location.pathname.lastIndexOf('/'))`, but it's not the best solution.

Let's say that your webapp is running under `/context-root/startpage`. How would you know if your root directory is `/context-root/startpage` or `/context-root`?

A better approach IMO could be implementing a `basePath` variable in front of `/meta.json`, so we can configure it when using the library: `useCacheClear({ basePath: '/context-root' })`.

**Comment by kris-pl83** [comment]
Hi,

I agree with @fedebabrauskas. 
Adding additional paremeter could be better solution.

Regards,
Kris

**Comment by greeksolid** [comment]
Hi,
First, thanks a lot for this package!
I just wanted to chime in to say that a "basePath" property would be awesome and solve my use case with Create React App.
