### ISSUE TITLE
Run "npm run generate-build-meta" in pre-build or post-build?

### ISSUE THREAD

**Issue by kharissa** [noahjohn9259/react-clear-cache#14]
Thanks for this package! I have a quick question: in the [instructions](https://www.npmjs.com/package/react-clear-cache), it says to run the script in `postbuild`:

```
  "postbuild": "npm run generate-build-meta",
  "generate-build-meta": "./node_modules/react-clear-cache/bin/cli.js"
```

However the [example package.json](https://github.com/noahjohn9259/react-clear-cache/blob/master/example/package.json) says to run in `prebuild`:
```
  "prebuild": "npm run generate-build-meta",
  "generate-build-meta": "./node_modules/react-clear-cache/bin/cli.js"
```
If it matters...which one is correct? Thanks in advance!

**Comment by fedebabrauskas** [comment]
Hi @kharissa!

It matters of course!

You need the `meta.json` file inside your build folder, so you need to run the script before doing any build of your webapp.

That's the only reason why you should use `prebuild` instead of `postbuild`.

In my opinion, the instructions are wrong, but the example is ok.
Some days ago I created a PR to fix the instructions, but it's not merged yet.

Hope I helped you to solve your problem, and sorry for the late response!

**Comment by noahjohn9259** [comment]
hi @kharissa , sorry for the late response. Got busy on delay work! @fedebabrauskas is right. The `meta.json` should be generated before the `build` script runs since it will look for all static scripts under the `public` folder.
